"""empty message

Revision ID: 15a25a005029
Revises: 40ea96786bdc
Create Date: 2014-03-08 22:30:19.720460

"""

# revision identifiers, used by Alembic.
revision = '15a25a005029'
down_revision = '40ea96786bdc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fb_username', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fb_username')
    ### end Alembic commands ###
