"""empty message

Revision ID: 189bab9a14e1
Revises: 275142357fa2
Create Date: 2014-03-28 18:59:30.935139

"""

# revision identifiers, used by Alembic.
revision = '189bab9a14e1'
down_revision = '275142357fa2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('accepted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friends', 'accepted')
    ### end Alembic commands ###
