"""empty message

Revision ID: 1abc9e5a3aeb
Revises: 4ba258fafa45
Create Date: 2014-02-23 15:41:07.124253

"""

# revision identifiers, used by Alembic.
revision = '1abc9e5a3aeb'
down_revision = '4ba258fafa45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fb_id', sa.String(length=255), nullable=True))
    op.drop_column('users', 'fb_oauth')
    op.create_unique_constraint(None, 'users', ['fb_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users')
    op.add_column('users', sa.Column('fb_oauth', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('users', 'fb_id')
    ### end Alembic commands ###
