"""empty message

Revision ID: 26398cf99dbf
Revises: 15a25a005029
Create Date: 2014-03-08 22:36:38.228397

"""

# revision identifiers, used by Alembic.
revision = '26398cf99dbf'
down_revision = '15a25a005029'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
