"""empty message

Revision ID: 275142357fa2
Revises: 3b7546542f3f
Create Date: 2014-03-28 00:05:23.645902

"""

# revision identifiers, used by Alembic.
revision = '275142357fa2'
down_revision = '3b7546542f3f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('status', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'status')
    ### end Alembic commands ###
