"""empty message

Revision ID: 3272e4564f32
Revises: 869fdb8805a
Create Date: 2014-03-08 21:58:36.906723

"""

# revision identifiers, used by Alembic.
revision = '3272e4564f32'
down_revision = '869fdb8805a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'display_name')
    ### end Alembic commands ###
