"""empty message

Revision ID: 329a671bdbd7
Revises: 32d5c449b7d7
Create Date: 2014-04-17 12:58:32.436013

"""

# revision identifiers, used by Alembic.
revision = '329a671bdbd7'
down_revision = '32d5c449b7d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('icon', sa.String(length=255), nullable=True))
    op.add_column('videos', sa.Column('title', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'title')
    op.drop_column('videos', 'icon')
    ### end Alembic commands ###
