"""empty message

Revision ID: 32d5c449b7d7
Revises: 795095f0c32
Create Date: 2014-04-06 21:00:37.187787

"""

# revision identifiers, used by Alembic.
revision = '32d5c449b7d7'
down_revision = '795095f0c32'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fb_id')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fb_id', sa.VARCHAR(length=255), nullable=True))
    op.create_index('users_fb_id_key', 'users', ['fb_id'], unique=True)

    ### end Alembic commands ###
