"""empty message

Revision ID: 40ea96786bdc
Revises: fc0e4007abd
Create Date: 2014-03-08 22:12:14.385437

"""

# revision identifiers, used by Alembic.
revision = '40ea96786bdc'
down_revision = 'fc0e4007abd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
