"""empty message

Revision ID: 4b3d0a4af3a7
Revises: 9c072d44a9e
Create Date: 2014-04-19 14:05:21.793549

"""

# revision identifiers, used by Alembic.
revision = '4b3d0a4af3a7'
down_revision = '9c072d44a9e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
