"""empty message

Revision ID: 4ba258fafa45
Revises: 2f30dcb96882
Create Date: 2014-02-18 23:45:38.834398

"""

# revision identifiers, used by Alembic.
revision = '4ba258fafa45'
down_revision = '2f30dcb96882'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    ### end Alembic commands ###
