"""empty message

Revision ID: 795095f0c32
Revises: 189bab9a14e1
Create Date: 2014-04-06 20:42:54.440358

"""

# revision identifiers, used by Alembic.
revision = '795095f0c32'
down_revision = '189bab9a14e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friends', 'accepted')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('accepted', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###
