"""empty message

Revision ID: 869fdb8805a
Revises: 19fb7461d42c
Create Date: 2014-03-01 22:47:57.892126

"""

# revision identifiers, used by Alembic.
revision = '869fdb8805a'
down_revision = '19fb7461d42c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friender_id', sa.Integer(), nullable=True),
    sa.Column('friendee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friendee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['friender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    ### end Alembic commands ###
