"""empty message

Revision ID: 9c072d44a9e
Revises: 329a671bdbd7
Create Date: 2014-04-17 15:39:10.242706

"""

# revision identifiers, used by Alembic.
revision = '9c072d44a9e'
down_revision = '329a671bdbd7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
